

class DataIngestionArtifact:...
class DataValidationArtifiact:...
class DataTransformationArtifiact:...
class ModelTrainerArtifiact:...
class ModelEvaluationArtifiact:...
class ModelPusherArtifiact:...